export const tempTreeData = [
  {
    title: "Big Tree",
    imgSrc: [
      "https://source.unsplash.com/random/400×300/?shrub",
      "https://source.unsplash.com/random/400×300/?shrub",
    ],
    sciName: "treeus maximus",
    intro:
      "Red Maple has an oval shape and is a fast grower with strong wood, reaching a height of 75 feet (Fig.   1). Unless irrigated or on a wet site, Red Maple is best used north of USDA hardiness zone 9. Trees are often much shorter in the southern part of its range unless growing next to a stream or on a wet site. This tree is preferred over Silver Maple or Boxelder when a fast growing Maple is needed. When planting the species Acer rubrum, select only those which have been grown from seed sources in your area. The newly emerging leaves and red flowers and fruits signal that spring has come. They appear in December and January in Florida, later in the northern part of its range. The seeds of red maple are quite popular with squirrels and birds. This tree if sometimes confused with red-leaved cultivars of Norway Maple.",
    sciInfo: {
      scientificName: 'tempinfo',
    commonNames: 'tempinfo',
    family: 'tempinfo',
    hardinessZone: 'tempinfo',
    origin: 'tempinfo',
    availability: 'tempinfo',
    },
    traits: {
      leafType: "simple",
      leafShape: "smooth",
      leafSize: 3,
      bark: "smooth",
      branches: "spiral",
      fruit: "fleshy",
      flower: "green",
    location: ["CA"],
    },
    uses: 'temp uses data',
  },
  {
    title: "Small Tree",
    imgSrc: [
      "https://source.unsplash.com/random/400×300/?tree",
      "https://source.unsplash.com/random/400×300/?bark",
      "https://source.unsplash.com/random/400×300/?apple",
    ],
    sciName: "treeus minimus",
    intro:
       "Red Maple has an oval shape and is a fast grower with strong wood, reaching a height of 75 feet (Fig.   1). Unless irrigated or on a wet site, Red Maple is best used north of USDA hardiness zone 9. Trees are often much shorter in the southern part of its range unless growing next to a stream or on a wet site. This tree is preferred over Silver Maple or Boxelder when a fast growing Maple is needed. When planting the species Acer rubrum, select only those which have been grown from seed sources in your area. The newly emerging leaves and red flowers and fruits signal that spring has come. They appear in December and January in Florida, later in the northern part of its range. The seeds of red maple are quite popular with squirrels and birds. This tree if sometimes confused with red-leaved cultivars of Norway Maple.",
    sciInfo: {
      scientificName: 'tempinfo',
    commonNames: 'tempinfo',
    family: 'tempinfo',
    hardinessZone: 'tempinfo',
    origin: 'tempinfo',
    availability: 'tempinfo',
    },
    traits: {
      leafType: "compound",
      leafShape: "toothed",
      leafSize: 6,
      bark: "rough",
      branches: "spiral",
      fruit: "acorn",
      flower: "white",
      location: ["MN", "IA", "WI", "IN", "IL"],
    },
    uses: 'temp uses data',
  },
  {
    title: "Good Tree",
    imgSrc: [
      "https://source.unsplash.com/random/400×300/?tree",
      "https://source.unsplash.com/random/400×300/?tree",
      "https://source.unsplash.com/random/400×300/?tree",
    ],
    sciName: "treeus awesomus",
    intro:
       "Red Maple has an oval shape and is a fast grower with strong wood, reaching a height of 75 feet (Fig.   1). Unless irrigated or on a wet site, Red Maple is best used north of USDA hardiness zone 9. Trees are often much shorter in the southern part of its range unless growing next to a stream or on a wet site. This tree is preferred over Silver Maple or Boxelder when a fast growing Maple is needed. When planting the species Acer rubrum, select only those which have been grown from seed sources in your area. The newly emerging leaves and red flowers and fruits signal that spring has come. They appear in December and January in Florida, later in the northern part of its range. The seeds of red maple are quite popular with squirrels and birds. This tree if sometimes confused with red-leaved cultivars of Norway Maple.",
    sciInfo: {
      scientificName: 'tempinfo',
    commonNames: 'tempinfo',
    family: 'tempinfo',
    hardinessZone: 'tempinfo',
    origin: 'tempinfo',
    availability: 'tempinfo',
    },
    traits: {
      leafType: "simple",
      leafShape: "lobed",
      leafSize: 4,
      bark: "peeling",
      branches: "drooping",
      fruit: "ball",
      flower: "green",
      location: ["MT", "ID", "NV", "OR", "CA", "WA"],
    },
    uses: 'temp uses data',
  },
  {
    title: "Pine Tree",
    imgSrc: [
      "https://source.unsplash.com/random/400×300/?tree",
      "https://source.unsplash.com/random/400×300/?tree",
      "https://source.unsplash.com/random/400×300/?tree",
    ],
    sciName: "Pinus Pinaceae",
    intro:
       "Red Maple has an oval shape and is a fast grower with strong wood, reaching a height of 75 feet (Fig.   1). Unless irrigated or on a wet site, Red Maple is best used north of USDA hardiness zone 9. Trees are often much shorter in the southern part of its range unless growing next to a stream or on a wet site. This tree is preferred over Silver Maple or Boxelder when a fast growing Maple is needed. When planting the species Acer rubrum, select only those which have been grown from seed sources in your area. The newly emerging leaves and red flowers and fruits signal that spring has come. They appear in December and January in Florida, later in the northern part of its range. The seeds of red maple are quite popular with squirrels and birds. This tree if sometimes confused with red-leaved cultivars of Norway Maple.",
    sciInfo: {
      scientificName: 'tempinfo',
    commonNames: 'tempinfo',
    family: 'tempinfo',
    hardinessZone: 'tempinfo',
    origin: 'tempinfo',
    availability: 'tempinfo',
    },
    traits: {
      leafType: "simple",
      leafShape: "needle",
      leafSize: 1,
      bark: "smooth",
      branches: "drooping",
      fruit: "cone",
      flower: undefined,
      location: ["MT", "ID", "NV", "OR", "CA", "WA"],
    },
    uses: 'temp uses data',
  },
  {
    title: "Happy Tree",
    imgSrc: [
      "https://source.unsplash.com/random/400×300/?tree",
      "https://source.unsplash.com/random/400×300/?tree",
      "https://source.unsplash.com/random/400×300/?tree",
    ],
    sciName: "treeus smilimus",
    intro:
       "Red Maple has an oval shape and is a fast grower with strong wood, reaching a height of 75 feet (Fig.   1). Unless irrigated or on a wet site, Red Maple is best used north of USDA hardiness zone 9. Trees are often much shorter in the southern part of its range unless growing next to a stream or on a wet site. This tree is preferred over Silver Maple or Boxelder when a fast growing Maple is needed. When planting the species Acer rubrum, select only those which have been grown from seed sources in your area. The newly emerging leaves and red flowers and fruits signal that spring has come. They appear in December and January in Florida, later in the northern part of its range. The seeds of red maple are quite popular with squirrels and birds. This tree if sometimes confused with red-leaved cultivars of Norway Maple.",
    sciInfo: {
      scientificName: 'tempinfo',
    commonNames: 'tempinfo',
    family: 'tempinfo',
    hardinessZone: 'tempinfo',
    origin: 'tempinfo',
    availability: 'tempinfo',
    },
    traits: {
      leafType: "simple",
      leafShape: "toothed",
      leafSize: 2,
      bark: "peeling",
      branches: undefined,
      fruit: "catkin",
      flower: "green",
      location: ["ME", "VT", "NH"],
    },
    uses: 'temp uses data',
  },
  {
    title: "Silly Tree",
    imgSrc: [
      "https://source.unsplash.com/random/400×300/?tree",
      "https://source.unsplash.com/random/400×300/?tree",
      "https://source.unsplash.com/random/400×300/?tree",
    ],
    sciName: "treeus goofus",
    intro:
       "Red Maple has an oval shape and is a fast grower with strong wood, reaching a height of 75 feet (Fig.   1). Unless irrigated or on a wet site, Red Maple is best used north of USDA hardiness zone 9. Trees are often much shorter in the southern part of its range unless growing next to a stream or on a wet site. This tree is preferred over Silver Maple or Boxelder when a fast growing Maple is needed. When planting the species Acer rubrum, select only those which have been grown from seed sources in your area. The newly emerging leaves and red flowers and fruits signal that spring has come. They appear in December and January in Florida, later in the northern part of its range. The seeds of red maple are quite popular with squirrels and birds. This tree if sometimes confused with red-leaved cultivars of Norway Maple.",
    sciInfo: {
      scientificName: 'tempinfo',
    commonNames: 'tempinfo',
    family: 'tempinfo',
    hardinessZone: 'tempinfo',
    origin: 'tempinfo',
    availability: 'tempinfo',
    },
    traits: {
      leafType: "compound",
      leafShape: "toothed",
      leafSize: 9,
      bark: "smooth",
      branches: undefined,
      fruit: "nut",
      flower: "orange",
      location: ["FL", "GA", "AL", "TN", "SC", "NC"],
    },
    uses: 'temp uses data',
  },
];